name: Dilithium3
type: sign
checksumsmall: 40ad143539d3b0284835a53a7e3ba9009aa263aa6cae651128bdd0f9ae22a558
checksumbig: e313580b88caae0535805b9ff89adb949d1e38dc7e9405a6d9efc6c13f90abb6
claimed-nist-level: 3
implementations:
    - name: amd64/ref
      version: 0.1
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
