name: 'work0'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        run: make -j8 -C src/ CI=1

      - name: artifact - src compilation log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: compilation-log
          path: src/check.tar.gz
