name: 'work0'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        run: make -C src/ CI=1
